listen=YES
listen_ipv6=NO
anonymous_enable=YES
local_enable=NO
write_enable=NO
anon_root=/var/ftp/pub
no_anon_password=YES
hide_ids=YES
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40100
xferlog_enable=YES
connect_from_port_20=YES
ftpd_banner=Welcome to the Tomb of Anubis FTP Archive.
max_clients=10
max_per_ip=2
delay_failed_login=3
delay_successful_login=1
idle_session_timeout=120
data_connection_timeout=120
anon_max_rate=65536
seccomp_sandbox=NO
secure_chroot_dir=/var/run/vsftpd/empty
